### ISSUE TITLE
Add a `references` section to the Module.yaml

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/module-packer#55]
Example:
```
references:
  - path: path/to/file
     name: Name
     slug: slug
     parent: Parent
     order: 1
```
